apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-apeb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-apeb
    app.kubernetes.io/part-of: ci10t-776-0098-app
  name: devfile-sample-apeb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-apeb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-apeb
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0098-tenant/ci10t-776-0098-app/devfile-sample-apeb@sha256:ad3287f67b4a7beab5d930a1d8686d09f64db5cee453bf4f2269c2ca4e83e503
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
